apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: eugeniaguzman
    app.kubernetes.io/version: '0a66b01'
  name: eugeniaguzman
  namespace: websites
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: eugeniaguzman
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: eugeniaguzman
        app.kubernetes.io/version: '0a66b01'
    spec:
      containers:
        - image: registry.digitalocean.com/munyaal-docr/website/eugeniaguzman:0a66b01
          name: eugeniaguzman
          ports:
            - containerPort: 8080
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: eugeniaguzman
  name: eugeniaguzman
  namespace: websites
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: eugeniaguzman
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eugeniaguzman
  namespace: websites
spec:
  ingressClassName: nginx
  rules:
    - host: eugeniaguzman.munyaal.com.mx
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: eugeniaguzman
                port:
                  number: 80       
  tls:
    - hosts:
        - eugeniaguzman.munyaal.com.mx
      secretName: munyaal-com-mx-tls